### ISSUE TITLE
No walking animation

### ISSUE THREAD

**Issue by phanbu** [phanbu/gamboge#1]
When player moves, the sprite image just floats around.  
There is no walking motion, no leg movement.

**Comment by CrossSpider3456** [comment]
I'll work on this one

**Comment by phanbu** [comment]
Basically, what needs to be done here is for the player image to be updated so that it looks like his legs are moving.  Do you have any experience with image editing?

**Comment by CrossSpider3456** [comment]
no

**Comment by phanbu** [comment]
I didn't want to leave you with the wrong impression after talking yesterday about where I put that comment in your code:

        # self.image = ...

Once your `__init__` method is finished it will be *possible* to write everything you need in one line.  However, you'll really end up with a block of code.  Something like this:

        if self.direction == DIRECTIONS['STOPPED']:
             # ....
        elif self.direction == DIRECTIONS ['UP']:
            #. ....
        elif self......

Respond here if you have questions.

**Comment by CrossSpider3456** [comment]
i was going to start working on my homework today and stupidly my program
doesn't run at the moment so i have to get it running but i need your help

**Comment by phanbu** [comment]
What is the error that you are getting?

**Comment by CrossSpider3456** [comment]
Traceback (most recent call last):
  File "C:/pycourse/gamboge/main.py", line 46, in <module>
    Game().run()
  File "C:/pycourse/gamboge/main.py", line 34, in run
    self.state.draw()
  File "C:\pycourse\gamboge\world.py", line 113, in draw
    self.game.screen.blit(sprite.image, self.camera.apply(sprite))
TypeError: argument 1 must be pygame.Surface, not str
libpng warning: iCCP: known incorrect sRGB profile

Process finished with exit code 1

**Comment by phanbu** [comment]
It looks like your problem is happening in this loop:

        for sprite in self.characters:
            self.game.screen.blit(sprite.image, self.camera.apply(sprite))

This makes me think that there is something in your `characters` sprite group that is a string--not a sprite.


Around line 89, you should have something that looks like this

        self.characters = pygame.sprite.Group()

and then a few lines later, 

        self.player = Player(self, 20, 20, self.characters)

Do you have both of these lines?  Is `self.characters` the fourth parameter when you create the new `Player`?

(Note:  I noticed that I have accidentally included the `AdventureState` class in world.py twice.  You can delete the first one from your code.)


Then, in sprites.py, does your Player class start something like this?

    class Player(Character):
        def __init__(self, game, x, y, *groups):
            super().__init__(game, x, y, groups)
            self.player_img = path.join(self.game.img_folder, 'p001.png')
            self.sprite_sheet = SpriteSheetGrid(self.player_img, 3, 4, color_key=None, has_alpha=True)
            self.image = self.sprite_sheet.get_image((0, 1))
            self.rect = self.image.get_rect()
            self.move_rect(self.position)

Most notably, the `groups` variable should be passed into the `super().__init()` method.  Also, note that in this version of the code, it is the fourth parameter (not counting `self`).

**Comment by phanbu** [comment]
@CrossSpider3456 's changes have been merged with the master.  

As @jhanbu and @CrossSpider3456 have both mentioned, the Player and NPC images are too big for the map.  I will work on fixing that this week.
